# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.mdw
- LICENSE
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
author: MentorFinder # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: MentorFinder # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://mentorfinder.cn
    - https://github.com/tip
    - https://github.com/mfrepo
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: TIP # Needed for Siteleaf
    output: true
    description: "Thought In Practice" # The post list page content
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "TIP" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/tip-no-bk.png" # Site logo, also used in jekyll-seo-tag
description: "TIP专注提供共创学习方法、思考框架、案例分享平台！" # Site description and default description, also used in jekyll-seo-tag
url: "https://mentorfinder.cn" # Site url, also used in jekyll-seo-tag
baseurl: "/tipHome"
repo: "https://github.com/mfrepo/tipHome"
email: "mentorfinder@163.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/tip-no-bk.png'
  32: '/assets/tip-no-bk.png'
  96: '/assets/tip-no-bk.png'
  120: '/assets/tip-no-bk.png'
  144: '/assets/tip-no-bk.png'
  180: '/assets/tip-no-bk.png'
  512: '/assets/tip-no-bk.png'
  1024: '/assets/tip-no-bk.png'

# 9. Site navigation
navigation_header:
- title: 主页
  url: /
- title: 分类
  url: /categories/
- title: 最新
  url: /blog/
- title: 搜索
  url: /search/
- title: 成为作者
  url: https://github.com/mfrepo/tipHome
- title: 关于我们
  url: https://mentorfinder.cn



navigation_footer:
- title: Copyright@MentorFinder
  url: https://mentorfinder.cn

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/mfrepo
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
